apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    purpose: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: playground
  labels:
    purpose: experiments
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    purpose: continuous-integration
